---
apiVersion: v1
kind: ConfigMap
metadata:
  name: explora-vr-server-config
  labels:
    app: explora-vr-server
data:
  FLASK_APP: 'run.py'
  APP_SETTINGS: 'production'
  QUERY_LOG: './issued_queries.log'
  ENABLE_TC: 'true'
  BANDWIDTH: '1gbit'
  LATENCY: '25'
  JITTER: '0'
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: explora-vr-server
  name: explora-vr-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: explora-vr-server
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: explora-vr-server-config
        image: gitlab.ilabt.imec.be:4567/lordezan/explora-vr-server
        name: explora-vr-server
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
      nodeSelector:
        explora-env: test
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred    
status: {}
