---
apiVersion: v1
kind: ConfigMap
metadata:
  name: explora-vr-server-config
  labels:
    app: explora-vr-server
data:
  FLASK_APP: run.py
  APP_SETTINGS: production
  QUERY_LOG: ./issued_queries.log
  ENABLE_PREFETCHING: true
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: explora-vr-server
  name: explora-vr-server
spec:
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: explora-vr-server
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: explora-vr-server-config
        image: gitlab.ilabt.imec.be:4567/lordezan/explora-vr-server
        name: explora-vr-server
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred    
status: {}
