apiVersion: v1
kind: Service
metadata:
  name: explora-vr-server
  labels:
    app: explora-vr-server
spec:
  type: LoadBalancer
  ports:
   - port: 80
     targetPort: 80
     nodePort: 30080
  selector:
   app: explora-vr-server